"""empty message

Revision ID: caf01159dc6a
Revises: 96fd03ddde1d
Create Date: 2025-06-19 13:35:31.636887

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'caf01159dc6a'
down_revision = '96fd03ddde1d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('authors', schema=None) as batch_op:
        batch_op.drop_constraint('authors_genre_id_fkey', type_='foreignkey')
        batch_op.drop_column('genre_id')

    with op.batch_alter_table('books', schema=None) as batch_op:
        batch_op.add_column(sa.Column('genre_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(None, 'genres', ['genre_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('books', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('genre_id')

    with op.batch_alter_table('authors', schema=None) as batch_op:
        batch_op.add_column(sa.Column('genre_id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.create_foreign_key('authors_genre_id_fkey', 'genres', ['genre_id'], ['id'])

    # ### end Alembic commands ###
